[project]
name = "update-local-wan-ip-nextdns"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "structlog>=25.3.0",
]
