apiVersion: v1
kind: Secret
metadata:
  name: nextdns-ip-updater-secrets
  namespace: homelab
type: Opaque
stringData:
  NEXTDNS_ENDPOINT: "https://link-ip.nextdns.io/YOUR_ID/YOUR_EXT_ID" # Replace with your actual endpoint
  UPDATE_INTERVAL_SECONDS: "300" # Default is 5 minutes, change if needed
